# 1) Redireciona todo tráfego do domínio Netlify para o customizado
[[redirects]]
  from       = "/*"
  to         = "https://meuprompt.eiaiflix.com.br/:splat"
  status     = 301
  force      = true
  conditions = { Host = "chimerical-lamington-3802a5.netlify.app" }

[[redirects]]
  from       = "/"
  to         = "https://meuprompt.eiaiflix.com.br"
  status     = 301
  force      = true
  conditions = { Host = "chimerical-lamington-3802a5.netlify.app" }

# 2) Força HTTPS no custom domain (opcional)
[[redirects]]
  from       = "http://meuprompt.eiaiflix.com.br/*"
  to         = "https://meuprompt.eiaiflix.com.br/:splat"
  status     = 301
  force      = true

# 3) Fallback SPA
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
